resources:
# Automation scripts repo
  - name: install_gce_nexus_repo
    type: gitRepo
    integration: "drship_github"
    versionTemplate:
      sourceName: "sample-organisation/install_gce_nexus" #TODO: change repo name to devops-recipes
      branch: master

# cliConfig for configuring gcloud cli
  - name: gcp_gcloud_cli
    type: cliConfig
    integration: "drship_gcp"

  - name: gcp_nexus_info
    type: params
    versionTemplate:
      params:
        SEED: "initial_version"

jobs:
# Install nexus on gce
  - name: install_gce_nexus
    type: runSh
    steps:
      - IN: gcp_gcloud_cli
      - IN: install_gce_nexus_repo
        switch: off
      - IN: gcp_gce_info
        switch: off
      - TASK:
          name: install_nexus
          runtime:
            options:
              env:
                - STATE_RES_NAME: "gcp_nexus_info"
          script:
            - pushd $(shipctl get_resource_state "install_gce_nexus_repo")
            - gcloud compute scp ./install_nexus.sh dev:~/install_nexus.sh --zone us-east1-d
            - gcloud compute ssh $gce_name --zone $gce_zone --command="chmod +x ~/install_nexus.sh"
            - gcloud compute ssh $gce_name --zone $gce_zone --command="~/install_nexus.sh"
            - shipctl put_resource_state_multi "$STATE_RES_NAME" "NEXUS_HOST=$INST_0_PUBLIC_IP"
            - popd
      - OUT: gcp_nexus_info
        overwrite: true
    flags:
      - gce_nexus
      - gce
      - nexus
